services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - smm_network
  
  brain:
    build: 
      context: .
      dockerfile: brain-api/Dockerfile.brain
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DEBUG=${DEBUG}
      - ADMIN_ID=${ADMIN_ID}
      - KAITEN_TOKEN=${KAITEN_TOKEN}
      - KAITEN_DOMAIN=${KAITEN_DOMAIN}
      - TZ=Europe/Moscow
    ports:
      - "127.0.0.1:8010:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/logs:rw
      - ./json:/json:rw
    networks:
      - smm_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000')"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 10s

  calendar:
    build: 
      context: .
      dockerfile: calendar-api/Dockerfile.calendar
    environment:
      - DEBUG=${DEBUG}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - TZ=Europe/Moscow
    ports:
      - "127.0.0.1:8011:8001"
    depends_on:
      - brain
    restart: unless-stopped
    volumes:
      - ./logs:/logs:rw
    networks:
      - smm_network

  executors:
    build: 
      context: .
      dockerfile: executors/Dockerfile.executors
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TP_API_ID=${TP_API_ID}
      - TP_API_HASH=${TP_API_HASH}
      - TP_PHONE_NUMBER=${TP_PHONE_NUMBER}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
      - TP_PASSWORD=${TP_PASSWORD}
      - DEBUG=${DEBUG}
      - KAITEN_DOMAIN=${KAITEN_DOMAIN}
      - TZ=Europe/Moscow
      - VK_USER_TOKEN=${VK_USER_TOKEN}
    ports:
      - "127.0.0.1:8013:8003"
    depends_on:
      brain:
        condition: service_healthy
    restart: always
    volumes:
      - ./logs:/logs:rw
      - ./sessions:/sessions:rw
    networks:
      - smm_network

volumes:
  postgres_data:
    driver: local
    name: smm_manager_postgres_data

networks:
  smm_network:
    driver: bridge